#!/bin/bash
# Print ICMP-reachable LAN nodes using ping
 
ping -c 2 -i 2 255.255.255.255 | awk ' $4 ~ /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/{print $4}' \
    | sed 's/\(.*\):/\1/g' | sort -n -t . -k1,1 -k2,2 -k3,3 -k4,4
