#!/bin/bash
#
# Send `pm-suspend` command to a remote host
# GNU Screen and pm-utils must be installed on the remote host
# The user must have SSH access to the remote host
# On the remote host, the user must have NOPASSWD settings for `pm-suspend`
# command in /etc/sudoers

cmd_name=$(basename $0)
usage="usage: $cmd_name HOSTNAME [USERNAME]"

[ $# -gt 2 -o $# -lt 1 ] && { echo "$usage" >&2; exit 1; }
hostname="$1"
username="$2"
[ -n "$username" ] && uri="$username@$hostname" || uri="$hostname"
session="sleephost"

ssh $uri "if ! screen -list | grep -E '\<[0-9]+\.$session\>' >/dev/null; 
    then screen -dmS $session; fi"
ssh -t $uri "screen -S $session -p 0 -X screen sudo pm-suspend"
