#!/bin/bash
# Start an SSH tunnel (SOCKS5)
# Port 8080 on localhost (127.0.0.1) will listen for requests and send them
# to the remote machine


CMD_NAME=$(basename $0)
HOSTNAME=$1
PORT=${2:-8080}
CMD="ssh -C2qTnN -D $PORT $HOSTNAME"
USAGE="usage: $CMD_NAME [username@]hostname [port]"

[ "$#" -gt 2 ] && { echo "$USAGE" >&2; exit 1; }
[ -n "$HOSTNAME" ] && { echo "$CMD"; $CMD; } || { echo "$USAGE" >&2; exit 1; }
