#!/bin/bash
# Start an SSH tunnel (SOCKS5)
# Port 8080 on localhost (127.0.0.1) will listen for requests and send them
# to the remote machine


cmd_name=$(basename $0)
cmd="ssh -C2qTnN -D 8080"


[ "$#" -eq 1 ] && { echo "$cmd $1"; $cmd "$1"; }
[ "$#" -ne 1 ] && { echo "usage: $cmd_name username@hostname"; }
