#!/bin/bash
# Start an SSH tunnel (SOCKS5)
# Port 8080 on localhost (127.0.0.1) will listen for requests and send them
# to the remote machine


cmd_name=$(basename $0)
hostname=$1
port=${2:-8080}
cmd="ssh -C2qTnN -D $port $hostname"
usage="usage: $cmd_name [username@]hostname [port]"

[ "$#" -gt 2 ] && { echo "$usage" >&2; exit 1; }
[ -n "$hostname" ] && { echo "$cmd"; $cmd; } || { echo "$usage" >&2; exit 1; }
